{% set name = "ipylab" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11433e172bc8984dbef9c80a0f27ece10e0e560adcff47af95979b6571e64fb6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.10,<1
    - python >=3.6
    - pip
  run:
    - ipywidgets >=7.6.0,<8
    - jupyterlab >=3.0.0,<4
    - python >=3.6

test:
  imports:
    - ipylab
  commands:
    - test -f "${PREFIX}/share/jupyter/labextensions/ipylab/package.json"

about:
  home: https://github.com/jtpio/ipylab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Control JupyterLab from Python notebooks

  dev_url: https://github.com/jtpio/ipylab

extra:
  recipe-maintainers:
    - jtpio
