{% set name = "ipylab" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3610a2903d22158e0bebf9e7aa53d1eb8286d3f2cef67ca0cdb59a09f0c7f6d0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - ipywidgets >=7.0.0
    - jupyterlab >=1.0.0
    - python >=3.5

test:
  imports:
    - ipylab

about:
  home: https://github.com/jtpio/ipylab
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Control JupyterLab from Python notebooks

  dev_url: https://github.com/jtpio/ipylab

extra:
  recipe-maintainers:
    - jtpio
